### ISSUE TITLE
Deal with ENCRYPTED attribute in FRAME

### ISSUE THREAD

**Issue by achaikou** [equinor/dlisio#103]
Per 5.7.1 Frame Objects Encrypted attribute is special
- If attribute is absent (code 000 or just not in the template), we should consider frame data not being encrypted.
-However, mere presence of this attribute should make record encrypted. It shouldn't matter if value is never explicitly specified, or if count is set to 0, or the value itself is 0/"".

Right now we drop all absent attributes anyway and do not proceed with attribute load if value is None. Hence we don't always process the value to explicitly make it True or False.

Current tests work because we specified encrypted = False by default, not None.

**Comment by ErlendHaa** [comment]
This got fixed in #200
