### ISSUE TITLE
Use scikit-ci-addons and overall improve CI experience

### ISSUE THREAD

**Issue by jokva** [equinor/dlisio#117]
In short, implement what @jcfr describes here https://github.com/equinor/dlisio/pull/116#issuecomment-496294297

A good opportunity to implement circle, too.

**Comment by jcfr** [comment]
When time will come, do not hesitate to ping me if you have any additional questions.

**Comment by jokva** [comment]
Will do, thanks for all your help so far, and for the work on scikit-build and the rest.
