### ISSUE TITLE
Bad segment trims

### ISSUE THREAD

**Issue by jhalotel** [equinor/dlisio#121]
Example: 
`padbytes (which is 168) >= segment.size() (which is 136)`

**Comment by achaikou** [comment]
com***009.dlis failing with message 
RuntimeError: bad segment trim: padbytes (which is 132) >= segment.size() (which is 124)

pol***136.dlis failing with message 
RuntimeError: bad segment trim: padbytes (which is 139) >= segment.size() (which is 60)

Provided file contain many encrypted data (handling of encrypted rows is not currently supported by DLISIO).

DLISIO doesn't handle correctly the following sentence from 2.2.2.1 comment 4:
'The Encryption bit indicates whether the Logical Record Segment Body and Pad Bytes (see comment 8) are encrypted.'

That means Pad Count is also encrypted. Hence we can't strip the padbytes before deciphering is done.
Currently we attempt to remove the padbytes, but if LRSL is less than 256 and last byte in encrypted data is bigger than LRSL, failure occurs.

After applying the temporary fix, both files have been read successfully.
PR is to follow.
