### ISSUE TITLE
'utf-8' codec can't decode byte 0xf4 in position 24: invalid continuation byte

### ISSUE THREAD

**Issue by jhalotel** [equinor/dlisio#126]

**Comment by GeoGerrit** [comment]
FunFact: U+00F4 is the unicode hex value of the character Latin Small Letter O with Circumflex.

**Comment by jokva** [comment]
It is, so my guess is that it's from a French field. We're developing a strategy for this.

**Comment by ErlendHaa** [comment]
Support for none-utf8 encodings was added in  #183. See https://dlisio.readthedocs.io/en/stable/intro.html#strings-and-encodings for how to deal with these. I will close this issue now.
