### ISSUE TITLE
Various faults that makes load crash from Python

### ISSUE THREAD

**Issue by cimka** [equinor/dlisio#138]
Version: 0.1.11

Faults:
-bad segment trim: padbytes (which is 232) >= segment.size() (which is 136)
-record-length in   record 135571 corrupted
-invalid argument
-file truncated
-'utf-8' codec can't   decode byte 0xfd in position 43: invalid start byte
-record-length in   record 1 corrupted
-unexpected   end-of-record

**Comment by ErlendHaa** [comment]
All these are covered by other issues
