### ISSUE TITLE
public vs private records

### ISSUE THREAD

**Issue by ErlendHaa** [equinor/dlisio#169]
Section 4.1.10 Logical Record Types of rp66v1 introduce the concept of private and public records. It is intended as a way of classify the audience of the records, producers of dlis-files and consumers. Only public records have semantic meaning to the consumer, i.e. the end users of dlisio.

At this point in time, dlisio do not care if a record is public or private. All records end in the same pool. From the end-users perspective, its not necessary obvious which records are meant for them. So because files often contains large amount of private vendor-specific records, I suggest we make a split between public and private records, to reduce noise.

I.e. the main pool of records should maybe only contain public records. And then we have a 'side-pool' of private records if someone is interested

**Comment by ShikhaMishra9** [comment]
As per dlisio specification document user can not send public records and it will mostly be private . So specific change for private and public not required .
