### ISSUE TITLE
Curves extraction from dlis

### ISSUE THREAD

**Issue by veritolilo** [equinor/dlisio#175]
Hi, 
As i mentioned before I am a new user of dlisio. I just started to use it few days ago.  I have had some problems to extract the curves from the dlis files. I have follow the tutorial and I always get an error. I thought that might be related to my procedure itself but then I discussed with a colleague who has more experience working with dlisio and seems that I am following the procedures.  I also tried with different dlis files to discard the possibility of corrupted file. In addition, for him the command line works so maybe there is a bug in the new dlisio version. 

Here I show part of my code: 
channel_dict={ ch.name: ch for ch in f.channels }  #generation of a dictionary for all the channels

cbl=channel_dict['CBL'] #selection of a single channel from the dictionary
print(cbl)
Channel(CBL)

cbl.frame # frame name from a channel object (ok)
Out[10]:
Frame(60B)

curve=cbl.curves() #curve extraction. 
print(curve)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-11-5abc356d31d4> in <module>
----> 1 curve=cbl.curves() #curve extraction =( maybe is there a bug in my dlisio version.
      2 print(curve)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\dlisio\plumbing\channel.py in curves(self)
    199         frame = self.frame
    200         pre_fmt, fmt, post_fmt = frame.fmtstrchannel(self)
--> 201         return curves(frame.file, frame, self.dtype, pre_fmt, fmt, post_fmt)
    202 
    203     def describe_attr(self, buf, width, indent, exclude):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\dlisio\dlisutils.py in curves(dlis, frame, dtype, pre_fmt, fmt, post_fmt)
     14     #note: shape is wrong for multiple data in one frame
     15     a = np.empty(shape = len(indices), dtype = dtype)
---> 16     core.read_fdata(pre_fmt, fmt, post_fmt, dlis.file, indices, a)
     17     return a

RuntimeError: ios_base::failbit set: iostream stream error

**Comment by ErlendHaa** [comment]
Hi

>  In addition, for him the command line works so maybe there is a bug in the new dlisio version.

Does that mean he is able to run your code but you are not? Can you check which versions of dlisio you are running? E.g by:  `print(dlisio.__version__)`

It would greatly help if you are able to supply the file, so we can take a closer look at whats going on

**Comment by veritolilo** [comment]
Hi, 
My colleague found the difference in the codes, and it seems to be an issue related to the way we open and read the dlis files. I have just tried now and it works.  

My first attempt was opening the files by using the commands from the tutorial (Dlisio Documentation) as follow: 

with dl.load('Well_16_1_9/16_1-9__WELL_LOG__WL_RAW_AAC-ARLL-CAL-DEN-GR-NEU-RMIC_RUN1_EWL_1.DLIS') as (f, *tail):
    f.describe()

By doing that I was always getting the error I showed before.  My colleague opens the files slightly different.  By using this command: 

f=dl.load('16_1-9__WELL_LOG__WL_RAW_AAC-ARLL-CAL-DEN-GR-NEU-RMIC_RUN1_EWL_1.DLIS')[0]
f.describe()

When I use this command I am able to extract the curves as it is pointed out in the documentation. 

channel_dict={ ch.name: ch for ch in f.channels } 
gr=channel_dict['GR'] #selection of a single channel from the dictionary
print(gr)
Channel(GR)
In [123]:

curve=gr.curves() #curve extraction command 
print(gr.frame)
print(curve)

Frame(60B)
[146.75058 146.75058 146.75058 ...  80.13261  76.17595  76.17595]

Both of us now we are working on the same dlisio version 0.1.13. 

Do you know what could be the reason for this discrepancies on the way of open the dlis files?

**Comment by ErlendHaa** [comment]
Hi,

That's peculiar. Do you by any change leave the scope of the `with`-statment before you call `*.curves()`

**Comment by veritolilo** [comment]
Now that mentioned, I think yes.  I am opening the files by using the with- statement and then other operations are out of the with.  So that means that I should perform all the operations inside the with statement? 
 for example: 

with dl.load('Well_16_1_9/16_1-9__WELL_LOG__WL_RAW_AAC-ARLL-CAL-DEN-GR-NEU-RMIC_RUN1_EWL_1.DLIS') as (f, *tail):
    f.describe()
    channel_dict={ch.name: ch for ch in frames[0].channels}
    channel_dict={ ch.name: ch for ch in f.channels } 
    gr=channel_dict['GR'] #selection of a single channel from the dictionary
    print(gr)
    curve=gr.curves() #curve extraction 
    print(gr.frame)
    print(curve)
 
As it as were a function?

**Comment by jokva** [comment]
> So that means that I should perform all the operations inside the with statement?

Yes. The file is kept open in the with-block, and deterministically closed when the with-block is exited.

**Comment by veritolilo** [comment]
Now it works =) fine using the with-statement  as well. That was the issue.  I didn't know that it works as function so I must keep all the operations inside.  However, it was kind of weird that I was able to access to the rest of the information being outside the with-statement.

**Comment by ErlendHaa** [comment]
The reason for that is that all the metadata objects like channels, frames, etc are loaded into memory when you open a file with `load`. So when you access these objects later on, they need not be read from disk again. However, the curve-data are read from disk on-demand, hence the filehandle must be open at the point where you do `.curves()`.

On a side note:
You can still use the `f, *tail = dlisio.load(file)` syntax, but then you should close `f` and the other files manually when you are done: `f.close()` etc.. The `with`-statment relieve you of that responsibility

**Comment by veritolilo** [comment]
Ok, thank you very much for the clarifications =).
