### ISSUE TITLE
Support encodings for all the components of chapter 3

### ISSUE THREAD

**Issue by achaikou** [equinor/dlisio#187]
Based on #183
Patch helps with correct encoding of string attribute values, but doesn't touch encoding errors.

Errors based on the patch:
- Encoding error on loading due to fingerprint processing (no correct encoding provided) - set names and object names.
- Could not allocate string object - template labels.
- SIGABRT - on encoded obname as value. Depending on the source of the error, it might appear that more tests are required.

The only situation encountered in real world is a fingerprint error on reading object name. Set is private and looks like it has been used to send information for private purposes.

Situation with object units and set names is unclear, as we do not return them to the user, so don't know if they are affected.

Tests would be submitted soon.

**Comment by ErlendHaa** [comment]
Point 1 should go away if fingerprint is byte string

**Comment by ErlendHaa** [comment]
The issues related to string encoding in fdata and obnames in general are solved, while the SIGABRT issues are described in more detail in #295, so I will close this issue
