### ISSUE TITLE
Allow empty strings in fingerprint

### ISSUE THREAD

**Issue by achaikou** [equinor/dlisio#190]
In certain situations our obname/objref/attref objects happen to be incorrect (empty).
When we attempt to load file containing objects like that, load fails with "invalid argument" error message. Once linkage is change as part of #169, error should appear only on accessing required object, but still wouldn't be helpful for the user.

Note small inconsistency (might be useful for #89):

- When attribute is not presented in the object (based on property that all non-mentioned attributes receive default value), the value we have for this attribute comes from defaulted_object - None. Thus attribute is not present in the resulting python object.
- When attribute is present, but is simply 20, we call patch_missing_value, which creates object with default values. For objref and obname these are not Nones.

According to specification both situations mean the same, so should behave the same.

**Comment by ErlendHaa** [comment]
The source of the error is when trying to create a fingerprint from an obname or objref with empy string(s). `dlis_object_fingerprint_size` deliberately throws if it there are empty string. All-though this is in accordance whit the dlis spec, we should probably lift this restriction

**Comment by ErlendHaa** [comment]
This is no longer as pressing as it once where as fingerprints are no longer used internally by dlisio. The current behaviour of lookup (done by logical_file.object) is to treat this as a "not found". This seams like a reasonable result for an object with no name and seing as this _is_ a spec violation we should keep this behavior. However before closing, test_link_empty_object in test_basicobject.py should be updated to reflect this behavior

**Comment by ErlendHaa** [comment]
Fingerprint are more or less phased out, so this is really not an issue anymore.
