### ISSUE TITLE
Allow duplicated channels in a frame

### ISSUE THREAD

**Issue by achaikou** [equinor/dlisio#191]
According to specification, frame is not allowed to have same channel twice as part of its channels list. If need arises, copynumbers are to be used.
We support this behaviour, as tested in `test_frames/test_duplicated_channels`, by raising error and logging a warning about duplicated mnemonics.

However the files producers do not always adhere to this obligation, as found about 80 files failing with the message (mostly DEPTH channel is affected).

Hence we might consider allowing duplicated channels in the frame in order to support such files.

**Comment by ErlendHaa** [comment]
Clear standard violation, add option to warn or throw
