### ISSUE TITLE
Lift restriction 'count (x) isn't 0 and representation code (y) changed, but value is not explicitly set'

### ISSUE THREAD

**Issue by achaikou** [equinor/dlisio#192]
Found around 15 similar files failing with this error message.
Template just defines the attribute with all the default data. One of the objects overrides reprcode but doesn't bother to provide value. Looks like either value wasn't important for this object, or simply is missing.

We might consider supplying any default value based on the new reprcode.

Current test: `test_parse/test_different_repcode_no_value`

**Comment by ErlendHaa** [comment]
Warn not throw

**Comment by ErlendHaa** [comment]
Resolved by #248
