### ISSUE TITLE
Consider support for wrongly marked FILE-HEADERS

### ISSUE THREAD

**Issue by achaikou** [equinor/dlisio#193]
Set can be defined like F0 (without name) and F8 (with name).
According to specification, FILE-HEADER Set should be unnamed. 

But in some files next happens:
- FILE-HEADER Set type is F8
- no name is provided.

This can happen to the first FILE-HEADER in the file or to the next ones. 
Right now we rightfully fail while parsing the set with "unexpected end-of-record in template" or "error parsing object descriptor".

We have around 45 files which break for this reason, but supporting them might not be practical.

**Comment by achaikou** [comment]
While this issue is relatively common (but still happens to way less than 1% of the files), supporting it appears to be too complex and unstable, hence not planned as of now.

Reasoning:
In case of general approach, supporting this issue requires recovery implementation. Failure happens in the set component and if we want to catch it we'll have to
- make dlisio more strict with regards to allowed template descriptors (to catch in time that what we see is not a template descriptor when it should be)
- implement recovery mechanism that will guess the actual template offset and test that the guess is correct.
While recovery is a difficult problem on its own, process happens to be very uncertain due to non-restrictiveness of dlis files.

Situation however may be reconsidered in the future if way more files with the same problem are found.

**Comment by ErlendHaa** [comment]
Additionally it's worth noting that this problem is not as big as it once where. In previous versions of dlisio this would hit at load, deeming the entire file unreadable. However the current parsing routines only parses object types that are explicitly asked for by the user. Meaning this will only hit you upon direct queries to the file header, while all other object types and curves will be unnaffected.

**Comment by ErlendHaa** [comment]
The effect of this is that the File-header objects cannot be read. Other than that the file is indexed and read correctly. As this is a hassle to fix and a very small issue, we are not gonna bother to fix this.
