### ISSUE TITLE
Consider support for wrongly handled invariant attributes

### ISSUE THREAD

**Issue by achaikou** [equinor/dlisio#194]
Attributes can be defined as invariant. In that case, they must not appear in object.

But in some files next happens:
- attribute is defined as invariant
- in following objects attribute is present as "20" (meaning 'take values from the template')

Right now we rightfully fail while parsing the set with "error parsing object descriptor"
Saw over 40 files which break for this reason, but supporting them might not be practical.

**Comment by achaikou** [comment]
While this issue is relatively common (but still happens to way less than 1% of the files), supporting it appears to be too complex and unstable, hence not planned as of now.

Reasoning:
True inconsistency happens between template and corresponding object attribute. 
However it won't be discovered in the very attribute which suffers from this issue because attribute is already marked as invariant, hence won't be checked for in the objects loop. Next attribute will be marked as "20", so "take default".
Hence error won't happen until two attributes from really problematic attribute, or even later, because as long as 1-byte value in place of the descriptor can be parsed as attribute/object descriptor, bytes afterwards can be interpreted. 
This means that perceived failure will happen way after actual failure offset.

Thus solution would have to consist of backtracking and recovery. 
In addition to complexity of backtracking/recovery problem on its own, these operations happen to be very uncertain due to non-restrictiveness of dlis files. 
Also due to the essence of the problem, code fixing it can't be generalized.

All of the above makes implementing support for it unfeasible.

Situation may be reconsidered in the future if way more files with the same or similar problem are found.

**Comment by ErlendHaa** [comment]
See above
