### ISSUE TITLE
Consider support for broken ORIGIN padbytes

### ISSUE THREAD

**Issue by achaikou** [equinor/dlisio#195]
In certain files ORIGIN object wrongly declares having padbytes (attributes has value 81). 
Last value in the record is actually 01, but it is because last attribute (Namespace version) ends on 01, not because of the padbytes.

Right now we rightfully fail while parsing the set with "unexpected end-of-record"
Around 10 seen similar files are affected, so supporting them might not be practical.

**Comment by ErlendHaa** [comment]
This is caused by the file being broken and only affect the Origin record, while the rest of the file can be read correctly. Not gonna fix
