### ISSUE TITLE
Return processed frame fdata on error

### ISSUE THREAD

**Issue by achaikou** [equinor/dlisio#196]
We should consider returning to user all the data we were able to read. 

Saw around 25 files where only last two lines contain something wrong, so all previous frames could be returned. 
We might also consider trying reading data from next LRs, but this cannot be supported by any real seen files. Saw around 25 files where only some frames are broken, but in this case failure happens on the lowest level of processing, so we never reach curves method.

**Comment by ErlendHaa** [comment]
Resolved by #296 (dd927f6f3e676579f2a84407391718ac0173dd48)
