### ISSUE TITLE
Consider removing cache from object

### ISSUE THREAD

**Issue by achaikou** [equinor/dlisio#203]
We often have lines like that as the first line of the method:
`if self._something: return self._something`

In many cases we support patching, like adding your own classes or changing existing values.

But caching (with no direct way of removing this cache) basically says: whatever was counted once will never be recounted again. So when user does sequence of actions:

1. get the cached property
2. do some patching affecting what property should be
3. get property again

User with receive old cached property anyway.

So we either should get rid of caching or explicitly state that all the patching is supported only before any actual work begins.

**Comment by jokva** [comment]
I support getting rid of caching, and maybe later re-introduce it for critial objects, if performance considerations dictate it.
