### ISSUE TITLE
Error when calling .curves() methon on a channel

### ISSUE THREAD

**Issue by scuervo91** [equinor/dlisio#204]
'
with dlisio.load(p) as (files,*tails):
    pass
frm=[]
for f in files.frames:
    frm.append(f)

chn=[]
for ch in frm[0].channels:
    chn.append(ch)
s=chn[0].curves()

I got the next error

`---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-60-1aec82edc335> in <module>
----> 1 s=chn[0].curves()

~\Anaconda3\envs\GG\lib\site-packages\dlisio\plumbing\channel.py in curves(self)
    215         frame = self.frame
    216         pre_fmt, fmt, post_fmt = frame.fmtstrchannel(self)
--> 217         return curves(frame.file, frame, self.dtype, pre_fmt, fmt, post_fmt)
    218 
    219     def describe_attr(self, buf, width, indent, exclude):

~\Anaconda3\envs\GG\lib\site-packages\dlisio\dlisutils.py in curves(dlis, frame, dtype, pre_fmt, fmt, post_fmt)
     14     #note: shape is wrong for multiple data in one frame
     15     a = np.empty(shape = len(indices), dtype = dtype)
---> 16     core.read_fdata(pre_fmt, fmt, post_fmt, dlis.file, indices, a)
     17     return a

RuntimeError: ios_base::failbit set: iostream stream error
`

How can I fix it?

**Comment by ErlendHaa** [comment]
Hi,

Looks like the file handle has been closed. Have you left the scope of the `with`-statement before calling `curves()`?

**Comment by ErlendHaa** [comment]
I'll close this issue now, as it has been inactive for a while. Feel free to open it again if you haven't solved your issue
