### ISSUE TITLE
Adjust for encoding in fdata

### ISSUE THREAD

**Issue by achaikou** [equinor/dlisio#206]
Encoding is supported for EFLRs, but not always for IFLRs, currently we receive error 'could not allocate string object' when utf-8 is broken. In actual files issue happens by accident when actual fdata is broken.
Existing test `test_fdata/test_broken_ut8_ascii`.

**Comment by ErlendHaa** [comment]
This can be cased by either 1) non-utf8 ident in the fdata obname or 2) if records is somehow truncated. 1 is solved as fdata now returns dl::ident, not std::string, while 2 is a particular case of #295
