### ISSUE TITLE
Propagate warnings from C

### ISSUE THREAD

**Issue by achaikou** [equinor/dlisio#207]
In parse.cpp we have methods "`user_warning`" and "`debug_warning`", which are intended to be used when there is a break in specification from the Chapter 3 processing level.
Right now methods are empty, so warnings are swallowed.

We also need consistent model of errors/warnings/infos/debugs to not overload user with a lot of broken, but recoverable, specification (which user probably doesn't really care about and doesn't know what to do with), but do not bury it and give user access to it on request.
Some tests in `test_parse` would expect these warnings.

**Comment by ErlendHaa** [comment]
resolved by #295
