### ISSUE TITLE
Consider getting back reprcode and count

### ISSUE THREAD

**Issue by achaikou** [equinor/dlisio#209]
Over 6 months ago a change was made to prevent passing attributes (reprcode, count, units) to python interface. Main point was to improve performance as attributes seemed not to be needed.

Separate request to bring back units already has been made as they are useful for the user.
Everything else (count, reprcode) is not, but it might be useful for us:
- For values presented straight in the objects (parameter, measurement, etc) we need to know what we are parsing. Now `sampling` method has to explicitly check whether object is a tuple.
- Reprcode might also be used in identifying 'link' objects instead of going by class instance, like now.

**Comment by ErlendHaa** [comment]
There is no need for it right now (if ever needed just add to `core.object_attribute`)
