### ISSUE TITLE
Consider checking for reamaining data after every read in parse

### ISSUE THREAD

**Issue by achaikou** [equinor/dlisio#210]
`parse.cpp`: currently we verify if we have more data only after reading set, template and object. 

It's unlikely that any of the actual files will fail because of this, as most of truncated data would fail in `findoffsets`. It however might happen in case of some new specification-break we haven't foreseen.
Tests `test_parse/cut_middle...`, do not fail now. More info in commit message `3bc16d`.

**Comment by ErlendHaa** [comment]
A particular case of #295
