### ISSUE TITLE
Consider supporting Storage Set

### ISSUE THREAD

**Issue by achaikou** [equinor/dlisio#212]
Refer to RP66 specification _2.3.4 Storage Set Requirements_.
Note that specification says: 

> "This typically need only occur with magnetic tapes, although it is permitted to occur with any type of Storage Unit. "

Also information about Storage Sets is present in _5.1 File Header_

Consider if it would be any good to support this somehow of if it doesn't give anyone any useful information.

**Comment by achaikou** [comment]
Might not be a problem worth immediate solving.

Up until now _Storage Unit Sequence Number_ == 1 in all the investigated files that have SULs, which means none of the files is a continuation of another physical file.
Which presumably means that we do not know about any case where same Logical File spans at least two physical files.
Situation however might be different for some old files which got digitized from tapes (if such files even exist).

Issue will be updated if any file breaking this assumptions will be found during further investigations.

**Comment by ErlendHaa** [comment]
Not gonna implement explicit support, see above
