### ISSUE TITLE
Consider supporting File Set

### ISSUE THREAD

**Issue by achaikou** [equinor/dlisio#213]
File Set somehow groups Logical Files. It's unclear whether this information is important for the user as 

> 'The File Set is an arbitrary grouping of a set of Logical Files and has no DLIS semantic meaning.'

More information in _5.2.1 Origin Objects_: FILE-SET-NAME, FILE-SET-NUMBER, FILE-NUBMER attributes.

**Comment by achaikou** [comment]
File Sets are used in real life.

From 5% to 10% of all investigated files had several logical files. Out of them around 50% have at least 2 different filesets.

Filesets are supposed to group logical files in some known manner.
However the way this feature is used in actual files remains unclear.

Explanation in specification is quite confusing, but most likely the idea was similar to the following:
- Defining origin defines fileset information for the logical file
- _file-set-number_ is used to identify filesets inside same Storage Unit Set
- _file-set-name_ just provides a useful name for the fileset identified by _file-set-number_. It's supposed to be the same for all logical files of the same fileset.
- _file-number_ is used to order logical files inside the fileset. It changes inside same fileset

Many files seem to adhere to this.

But from specification arise some issues like:
- it's not explicitly stated that defining origin must contain all the information about fileset. Other origins are supposed to be ignored or repeat the same information?
- _file-set-number_ doesn't have to be unique (even inside same Storage Unit Set)
- _file-set-number_ is hoped to be unique across all of the filesets in the world
- _file-set-name_ is not expected to be unique
- it's not fully clear what happens when _file-set-name_ is not present and _file-set-number_ is the same

   > [File-Set-Number] must be present, even when the File-Set-Name Attribute is absent. In that case, it is considered to apply to the File Set consisting of the single current Logical File. 

Very small number of files have been investigated manually, but already some unclear cases are seen:
- Some sets of logical files have same _file-set-name_, but change both _file-set-number_ and _file-number_ (_file-number_ is changed sequentially, which raises suspicions).
- Some sets of logical files have no _file-set-name_, but change both _file-set-number_ and _file-number_ (_file-number_ also sequentially)
- Some sets of logical files have same _file-set-name_ and _file-number_, but have different _file-set-number_ (which seems to be fine?)

It might mean that every file belongs to different fileset as per specification, or it might not.
Also:
- Some files repeat same fileset information in every origin
- Some files use low _file-set-number_, indicating they do not expect logical files to be likely uniquely identifiable across all dlis files existing in the world


Filesets also seem to have little value for the user.

So better decision might be to avoid explicit support of filesets and leave it to the user to combine bits-and-pieces when needed.

**Comment by ErlendHaa** [comment]
Not gonna implement explicit support, see above
