### ISSUE TITLE
'utf-8' codec can't decode byte 0xb0 in position 2: invalid start byte

### ISSUE THREAD

**Issue by mandeeps708** [equinor/dlisio#22]
Hi,

I was using this library to read the dlis files. I iterate over the records one by one and extract the headers as:

```python
    dl = dlisio.load(dlis_file_name)
    ...
    record = dl.fp.eflr(dl.bookmarks[i])
```

As we know, there can be multiple PARAMETER headers in a dlis file. So the first occurrence of parameter header is throwing this exception:

```python
'utf-8' codec can't decode byte 0xb0 in position 2: invalid start byte
```

other occurrences of parameters have been extracted fine.

The error is in the line:
```python
    record = dl.fp.eflr(dl.bookmarks[i])
```

where `i` is the loop variable that I used to refer to the records one by one.

I checked a few other dlis files and similar happens there also. Please point me if I am doing something wrong and let me know if you need me to provide any more information by debugging or anything else.

Thanks.

**Comment by jokva** [comment]
Hi,

This project is nowhere near production ready, and is under heavy development. Let me just say that we very much appreciate the testing and reporting you're doing for us.

Now, what you're doing is _not_ fine in the sense that the `fp.eflr` feature is for testing internal details. If these files are public and available (and preferably possible for me to re-distribute) I can add them to our test suite to make sure that these parameter header fields are read correctly.

On the other hand, what we're designing now is more robust parsing and exposing of the log metadata found in the explicit sections. I'll try to release another alpha with these features as soon as they're ready, in which case you will have a better (but not stable!) interface available for reading well parameters.

That exception usually comes from either broken or private or some other weirdness in the object name string that isn't valid 7-bit ascii. I've seen these pop up in several files, but for now I've just ignored them as other issues have been more pressing.

There's unfortunately not much more I can do for you other than ask you to be patient, and say that once these features mature and stabilise I'll write some examples and documentation for you.

**Comment by mandeeps708** [comment]
> Hi,
> 
> This project is nowhere near production ready, and is under heavy development. Let me just say that we very much appreciate the testing and reporting you're doing for us.

Thanks for your good work.

> Now, what you're doing is _not_ fine in the sense that the `fp.eflr` feature is for testing internal details. If these files are public and available (and preferably possible for me to re-distribute) I can add them to our test suite to make sure that these parameter header fields are read correctly.
 
I couldn't find the README/docs so that's what I could come up with, without diving deep into the dlisio code.
Can you please let me know the **right way** to parse the file instead of using `fp.eflr`?

> On the other hand, what we're designing now is more robust parsing and exposing of the log metadata found in the explicit sections. I'll try to release another alpha with these features as soon as they're ready, in which case you will have a better (but not stable!) interface available for reading well parameters.

Thanks. Waiting for it.
 
> That exception usually comes from either broken or private or some other weirdness in the object name string that isn't valid 7-bit ascii. I've seen these pop up in several files, but for now I've just ignored them as other issues have been more pressing.

Alright.

> There's unfortunately not much more I can do for you other than ask you to be patient, and say that once these features mature and stabilise I'll write some examples and documentation for you.

Thanks. It works fine most of the time at least for whatever is implemented. It would be great to have a basic usage in the README.md file.

**Comment by jokva** [comment]
> I couldn't find the README/docs so that's what I could come up with, without diving deep into the dlisio code.

It's not written yet. :---)

> Can you please let me know the right way to parse the file instead of using fp.eflr?

Ironically, that's more-or-less the right way, currently, if you want to read explicit records. If you want a specific channel's frame data for some object, you can use the `f.getcurves(CURVENAME)`.

None of these interfaces are expected to persist into something supported, but I won't remove it for a while (and these early alpha preview releases will not change, obviously).

**Comment by mandeeps708** [comment]
Hi @jokva ,

Thanks for your replies.

> Now, what you're doing is _not_ fine in the sense that the `fp.eflr` feature is for testing internal details. If these files are public and available (and preferably possible for me to re-distribute) I can add them to our test suite to make sure that these parameter header fields are read correctly.

Here is the file:

https://www.dropbox.com/s/suin9zh6dnz0gyf/0002_04_K_22_Splitshot_2_correlating_pass_ConCu_R4L4Up_HSD_CCL__04Dec13_173047_Edited_2014Apr02164221%281%29.dlis?dl=0

The first occurring PARAMETER header in the above file is throwing that exception.

> There's unfortunately not much more I can do for you other than ask you to be patient, and say that once these features mature and stabilise I'll write some examples and documentation for you.

One another big thing that I still need to figure out is a way to read the ASCII header. Can you please let me know a way, if it's possible?

Actually, I am reading the dlis files and writing the output as las. So ASCII (~A) header is an important header to be even able to write to las. Right now, I am using some dummy data created by me. But as you know, START, STOP and STEP attributes' value are taken from the data of ASCII header.

Thanks for the help.

**Comment by mandeeps708** [comment]
> > One another big thing that I still need to figure out is a way to read the ASCII header. Can you please let me know a way, if it's possible?
> 
> You can look through the pre-parsed explicit records in `f.explicits` and see if you find it there. If you pass that to `pprint` you get a pretty good idea on where to look for it.

Did you mean `fp.explicits`? But I can't find it either.

Here is how I am doing it (IPython):

```python
In [1]: import dlisio
In [2]: dl = dlisio.load("some_dlis_file.dlis")
```

On pressing dl. `<tab>`  it shows methods to select from (for autocomplete):
               
```                                       
             dl.bookmarks  dl.raw_record                                                                                                  
             dl.close      dl.sul                                                                                                         
             dl.fp                                               
```

On doing the same with `dl.fp.`<tab>:
```                                                      
                dl.fp.close      dl.fp.mkindex    
                dl.fp.eflr       dl.fp.raw_record 
                dl.fp.eof      
```

Thanks.

> Thanks for the file!

**Comment by jokva** [comment]
https://github.com/Statoil/dlisio/blob/master/python/dlisio/__init__.py#L17

I meant this, so `dl.explicits`. It's an attribute, so it might not show up. Did it crash when you tried?

**Comment by mandeeps708** [comment]
Hi @jokva 

Sorry, the environment I was looking into, was having an older version of dlisio.

Now I updated dlisio and now I can see the new additions like `explicits`.

Here is the `dl.explicits` output of the dlis file I sent earlier:

https://gist.github.com/mandeeps708/c6c7c0d9934062d5dfe7f4158880c4f3

But I couldn't seem to find the data. Am I missing something?

Thanks.

**Comment by mandeeps708** [comment]
Hi @jokva,

Sorry couldn't reply due to my limited knowledge (also priorities keep changing). Yes, I was talking about the frame data. `getcurves` and frame record did the trick hitherto.

You can close this issue now. I'll open a new relevant one if needed.

Thank you very much for the help.

**Comment by jokva** [comment]
Ok, great. Since then, the underlying engine has been refactored, and the getcurves interface is gone from the latest previews. We're currently experimenting mostly with metadata, so right now curves aren't even available.

Once we have something fit for general use, we'll write a nice readme and some documentation. Please stay tuned, I hope dlisio will be useful for you in the future.

**Comment by jokva** [comment]
@mandeeps708 For what it's worth, while the getcurves interface is gone, your contribution helped us figure out what exactly caused this error, and then fix it. Hopefully your file should work with future versions of dlisio, even though we aren't currently giving you access to curve data.
