### ISSUE TITLE
Pay more attention to Predecessor attribute

### ISSUE THREAD

**Issue by achaikou** [equinor/dlisio#222]
Saw the following file:
Fdata segment (first in the VR) declares attributes "`41`" - so predecessor present, no successor. Bytes that follow do not resemble fdata obname, but _findfdata_ thinks this is a new LR (as previous declared no successor) and attempts to read bytes as obname and fails with encoding error message.
Previous LRS didn't declare any successor and length was consistent with other frames of the same type. Looks like some VR was just lost along the way.

Having additional check for predecessor attribute would have helped to catch this situation and handle it better. 
It's however possible (but not 100% sure) that some of the files do not pay attention to this attribute, using successor only to assure continuity of records and do not setting predecessor bit.

**Comment by achaikou** [comment]
Based on investigated files, there is the same emphasis on predecessor attribute as it is on successor. Which means that it can be believed.

**Comment by ErlendHaa** [comment]
This is most fixed
