### ISSUE TITLE
Consider lifting minimal LR and VR size restriction

### ISSUE THREAD

**Issue by achaikou** [equinor/dlisio#227]
According to specification, VR length should be no less than 20 bytes and LRS length should be no less than 16 bytes. In case when data doesn't fit these conditions, padding should be used.

Saw a file where minimal size restriction was ignored.
Last LRS had to contain just two bytes, so sequence was as following
`"00 0A FF 01 00 06 C0 XX xx xx"`

Currently this restriction helps to fail early in case of broken files, but it shouldn't be a big problem if check "remaining >= lrs_length" is in place (check is missing now, which results in us failing later than we could, hence making investigation more difficult)

**Comment by ErlendHaa** [comment]
If this is to be fixed, point 2 and 3 in #102 should be in place
