### ISSUE TITLE
dlis.object() erroneously reports multiple parameters with the same name

### ISSUE THREAD

**Issue by erlendviggen** [equinor/dlisio#233]
I've found the dlis.object() function to be a very convenient way to get channels with unique names in a file. However, when I try to do this with parameters, the function throws an error:

    file.object('parameter', 'FN')

results in the error 

    ValueError: There are multiple parameters named FN. Found: (origin=57, copy=0), (origin=57, copy=0), 

I get the same error for any parameter I try. The parameters are not in fact multiply defined; this code returns `1` as you would expect:

    parameters = [par for par in file.parameters if par.name == 'FN']
    len(parameters)

I have verified that the error occurs on multiple log files from the public [Volve Data Village](https://www.equinor.com/en/how-and-why/digitalisation-in-our-dna/volve-field-data-village-download.html) data set. In no case did the error not occur.

This is of course not a serious problem, as the second approach works quite well for picking out named parameters as well. But is this problem due to a bug in dlisio, or am I simply using dlis.object() wrong?

**Comment by jokva** [comment]
This looks like a bug.

**Comment by ErlendHaa** [comment]
Definitely a bug, fixed it in #234, which is a part of v0.1.16 [1] that just got released

[1] https://github.com/equinor/dlisio/blob/master/CHANGELOG.md

**Comment by erlendviggen** [comment]
I can confirm that this now works perfectly for me in 0.1.16.
