### ISSUE TITLE
Move SUL-related information to Batch object

### ISSUE THREAD

**Issue by achaikou** [equinor/dlisio#240]
Currently dlis class represents one Logical File, but it still contains information about sul (_sul_offset_ attribute, _storage_label_ function). However SUL is file-related information, not logical file one, hence keeping it in Batch object makes more sense. 

*weird cases where SUL is repeated before every Logical File may be a problem (if we would support this kind of broken files)

**Comment by ErlendHaa** [comment]
Agreed!

As a side-note, both `batch` and `dlis` should probably be renamed to capture that they are representing physical- and logical files.

**Comment by ErlendHaa** [comment]
See no benefit off doing this because 1) there exist files with one SUL pr LF and 2) the SUL will be gone when using automatic tuple-unpacking in load.
