### ISSUE TITLE
Improve dealing with duplicated objects

### ISSUE THREAD

**Issue by achaikou** [equinor/dlisio#241]
Some files have a number of duplicated objects. 
When we have two objects with same `type/name/origin/copynr` combination, it's a specification violation that we can't easily bypass. When other object refers to this signature, we do not know what object it actually wants to refer to.
If we see objects with the same signature, we use only one of them (put into `indexedobjects`). Others get dropped in `problematic` and if users miss the warning they might not be aware of issues this might cause.

- Give user nice guide/method how to access `problematic `objects and swap them with the ones they want in `indexedobjects`.
- When we find same objects, we might need to compare attics. If all the attributes are the same, we can safely assume this is the same object and avoid the problem.
- Wherever we are linking to an object or user accesses such link, we might check if it is present in `problematic` objects and remind user if there is duplication.

`frame.curves(strict=False)`: while following situation is not likely to happen, it probably won't raise any red flags and user might rely on incorrect data without knowing it.

If we find duplicated objects in frame we might check if there actually are several objects with the same signature.
- If there is just 1, then we can treat this as a minor specification violation.
- If there are several different objects, we need to explicitly inform user about that. Additionaly, if we have wrong of two channels with different representation codes linked to the frame, we might read the data incorrectly. Best case we would fail on reading, but in case where reprcodes take the same amount of bytes and can be interpreted any way, we will serve incorrect data.

**Comment by ErlendHaa** [comment]
The above situation is outdated at this point, and the current behaviour is regarded as good! Any changes would be related to replacement/redundant sets (#214) and/or Update objects (#216)
