### ISSUE TITLE
UnicodeDecode Error

### ISSUE THREAD

**Issue by gracoba** [equinor/dlisio#244]
Hi,

I am trying to figure out which encoding will work with a specific DLIS file, but after test all possibilities the following error appears. How to solve it?

I have read the previous issues but the solution did not work.

Thanks for yout help

######  ===============         Error message          ===================

  File "/Work/anaconda3/lib/python3.7/site-packages/dlisio/__init__.py", line 783, in load
    part['implicits'], part['tells'], part['residuals']):
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 25: invalid start byte

######  ===============         CODE          ===================

    import dlisio
    import pandas as pd
    import numpy as np
    import matplotlib.pyplot as plt
    import unicodedata

    arquivo=<filename.dlis>
    codigos = ['ascii',
    'big5',
    'big5hkscs',
    'cp037',
    'cp273',
    'cp424',
    'cp437'
      ] 

    for codigo in codigos:
    	# decodificação dos caracteres 
    	print(codigo)
    	dlisio.set_encodings([codigo])

    	try:
		    with dlisio.load(arquivo) as files:
		        files.describe()
                    print('=========  FUNCIONOU =========')
    	except ValueError:
		    print('nao funcionou')
		    pass

**Comment by ErlendHaa** [comment]
Hi

I suspect that you have run into a different issue than first meets the eye here. 

Some dis-files are wrapped in a Tape Image Format (tif)  (see https://github.com/equinor/dlisio/issues/179, https://github.com/equinor/dlisio/issues/174), which the current version of dlisio does not support. What this essentially means is that there are some extra bytes here and there in the file.  So whenever a tape mark is encountered dlisio tries to interpret it as a part of the dlis data, which in turn fails. Either straight away or a bit later down the road .

In your file it hits you when dlisio tries to interpret the wrong bytes a string. Hence the unicode error.

We are currently working on tif support, and expect it to be part of the next release.

**Comment by gracoba** [comment]
Hi

thanks for you explanation. Based on your answer one colleague  will check this specific file to confirm if it was wrapped in Tape Image Format and I will keep updated.

Thanks again

**Comment by achaikou** [comment]
Other possibility:
Based on the error message most likely explanation is bug #188 . We also hope to fix this one soon along with tif support.

**Comment by gracoba** [comment]
@ErlendHaa based on your answer, We checked if the file is a TIF but it is not the case.

I copied the exception error. @achaikou, do you think is the case describe on  #188 ?

    An exception of type UnicodeDecodeError occurred. Arguments:
    ('utf-8', b'T.FRAME-I.PROVISION_RAW \x00\xff\x01\x1f\xfc`\x00_D-O.53-C.0', 25, 26, 'invalid start byte')

**Comment by achaikou** [comment]
Yes, it is.
Error message fits precisely to #188. (Frame name is interrupted by new VR ` \x00\xff\x01` and then LR `\x1f\xfc` )

**Comment by ErlendHaa** [comment]
The newest version of dlisio, v0.2.1, fixed #188 so your file loads correctly now. Closing this issue, but feel free to re-open it, if you are still having the issues.
