### ISSUE TITLE
Convenience feature suggestion: Show index units in Frame.describe()

### ISSUE THREAD

**Issue by erlendviggen** [equinor/dlisio#251]
Frame objects already have fields showing the minimum and maximum values of the index channel (`Frame.index_min` and `Frame.index_max`) and the spacing of the index channel (`Frame.spacing`). All of these are shown in `Frame.describe()`. However, the values of these fields do not mean much unless we know what physical units they are represented in.

While it is easy enough for the user to find this information by finding the index channel and getting its units, it would be more convenient if these units are shown as a field in `Frame.describe()`. Perhaps the index units could also be a field of Frame objects?

**Comment by ErlendHaa** [comment]
Hi

Including it in `Frame.describe()` is definitely an option to consider. 

Adding `Frame.units` I'm more hesitant about. All our metadata objects (`Frame`, `Origin`, `Tool`) and their fields are true to the DLIS spec, and we would like to keep it that way. However, a thought for the future could be to add  _enriched_ objects that contains more information than just the raw objects. `index_units` would be a natural enrichment to `Frame`

**Comment by ErlendHaa** [comment]
Hi,

Release 0.2.6 adds the index channel's units to `Frame.describe()`. Sorry this took so long.  It also adds units to `Frame.index_min` and `Frame.index_max`. Note how they can be different from the actual channel's units. E.g. from our test file `python/data/206_05a-_3_DWL_DWL_WIRE_258276498.DLIS`:

```
-----
Frame
-----
name   : 800T
origin : 2
copy   : 0

Channel indexing
--
Indexed by       : TIME
Index units      : ms
Index min        : 33354518 [0.5 ms]
Index max        : 35194520 [0.5 ms]
Direction        : INCREASING
Constant spacing : 800 [0.5 ms]
Index channel    : Channel(TIME)

Channels
--
TIME TDEP ETIM LMVL UMVL CFLA OCD  RCMD RCPP CMRT RCNU DCFL DFS  DZER RHMD HMRT
RHV  RLSW MNU  S1CY S2CY RSCU RSTS UCFL CARC CMDV CMPP CNU  HMDV HV   LSWI SCUR
SSTA RCMP RHPP RRPP CMPR HPPR RPPV SMSC CMCU HMCU CMLP
```
