### ISSUE TITLE
ValueError: month must be in 1..12

### ISSUE THREAD

**Issue by FDB-PG** [equinor/dlisio#255]
I have >2000 borehole image logs that I am bulk processing into a single resistivity curve from all the available data within each channel. 

A number of these DLIS files return value errors 

ValueError: month must be in 1..12

I am not sure how I can get around this error, so any feedback will be much appreciated.

Thanks,
Fabian

channel_dict_ = ['DEPT','DEPTH','BT1L','BT1U','BT2L','BT2U','BT3L','BT3U','BT4L','BT4U','BT5L','BT5U','BT6L','BT6U','BT7L','BT7U','BT8L','BT8U']

total_start = time.time()

cmi = pd.DataFrame()
list_ = []
df = pd.DataFrame()

list_ = []
df = pd.DataFrame()
n = 0
with dl.load(r'H:\\well_name.dlis') as (f, *tail):
    channel_dict={ ch.name: ch for ch in f.channels }
    for ch in channel_dict_:
        try:
            c=channel_dict[ch]
            curve = np.around(c.curves(),4)
            print(c)
            list_.append(curve)
            try:
                df2 = pd.DataFrame(list_[n])
                i = 0
                for cl in df2.columns:
                    df2.rename(columns = {df2.columns[i]:ch+'_'+str(i)}, inplace = True)
                    i = i+1
            except:
                df2 = pd.DataFrame(np.reshape(list_[n], (len(list_[n]),-1)))
                i = 0
                for cl in df2.columns:
                    df2.rename(columns = {df2.columns[i]:ch+'_'+str(i)}, inplace = True)
                    i = i+1
            n = n+1
            df = pd.concat([df,df2], axis =1, sort = False)
        except (KeyError):
            pass

Traceback (most recent call last):

  File "<ipython-input-26-937c494e152a>", line 12, in <module>
    with dl.load(r'H:\\well_name.dlis') as (f, *tail):

  File "C:\Users\Fabian.Brandimarte\AppData\Local\Continuum\anaconda3\lib\site-packages\dlisio\__init__.py", line 787, in load
    part['records'], implicits, sul_offset=sulpos)

  File "C:\Users\Fabian.Brandimarte\AppData\Local\Continuum\anaconda3\lib\site-packages\dlisio\__init__.py", line 232, in __init__
    self.load(recs)

  File "C:\Users\Fabian.Brandimarte\AppData\Local\Continuum\anaconda3\lib\site-packages\dlisio\__init__.py", line 624, in load
    for name, o in os.objects.items():

ValueError: month must be in 1..12

**Comment by achaikou** [comment]
Hi!
Thanks for reporting this issue.

What most likely happens is that some date in your file is invalid, most likely in one of the Origin objects.
Several other files with this problem have dates like "2048-00-00 00:00:00" or "2000-01-00 00:00:00".
As this date is broken, when we create a python object from it, we receive an error from datetime module.

Interesting thing is that in python 3.5 this doesn't result in a fatal error. Python will just create an invalid date with month "0". As investigation showed, from python 3.6 an error will be thrown.
So you might use this as a workaround for now and downgrade your python version to python 3.5.

As a permanent solution we would want to fail on this only when access to actual object is requested. 
Our future plans include moving more code into C, which might make it easier, so we postpone it until then.

**Comment by ErlendHaa** [comment]
This is caused by the datetime module and there is not really anything dlisio can do.
