### ISSUE TITLE
Feature request. Add .lis support.

### ISSUE THREAD

**Issue by BEEugene** [equinor/dlisio#258]
It would be nice if the package will be able to open *.lis files.

**Comment by ErlendHaa** [comment]
Hi

LIS and DLIS are two different formats with almost no common semantics. Thus this is a new library request more than a feature request. All I can do for you at this point is to point you to [TotalDepth](https://totaldepth.readthedocs.io/en/latest/), another open-source python library for reading well logs. It support for `.lis` files

**Comment by BEEugene** [comment]
@ErlendHaa, Thank you very much! Don't you know if there any libraries which support *.LTI format?

**Comment by ErlendHaa** [comment]
Not as far as I know
