### ISSUE TITLE
Duplicated objects

### ISSUE THREAD

**Issue by Nagaraju10** [equinor/dlisio#263]
Hello,
My Name is Nagaraju Reddicharla and have a geophysics background.

I am doing research work on DLIS files and am using DLISIO (equinor) python library to extract the data.  I find the DLISIO library is very useful and would like to congratulate on your work and contribution to the industry.
I am writing this email to get your insight on one of the issue that am facing for quite sometime. Hope you can help me in this regard.

I have an issue with duplicated objects in DLIS files and it is throwing an error and it says unable to extract the files using DLISIO. The documentation says that by making strict = False, the problem can be resolved. However this is not working.

Problematic
Duplicated objects. If dlisio is not able to uniquely identify an object based on the standards definition, the object is flagged as problematic. Mainly intended for debugging files

Kindly could you help and guide me on how to handle this issue. Attached error [mes
![duplicate objects error](https://user-images.githubusercontent.com/66116134/83245576-f92d4b80-a1b1-11ea-936a-1ccba97e9abb.JPG)
sage](url)

Hoping for your reply

Thank you in advance

**Comment by ErlendHaa** [comment]
Hi

Great to hear that you find the library useful! 

You have indeed found the right approach for this problem with `frame.curves(strict=False)`. What errors do you get when using it? Note that the argument strict is not yet a part of any official release, so you would have to build dlisio from source to use it at the moment. We are planing a new release shortly.

**Comment by Nagaraju10** [comment]
Thank you for quick response.  I am getting an error saying 'name false is not defined', Attached the error message with this email.  It is quite common here when a service provider generates the log, depth column is duplicated in the logs.  
Could you guide me/ provide me a work around on how to handle the issue to extract the data?
![duplicate](https://user-images.githubusercontent.com/66116134/83256648-dad04b80-a1c3-11ea-88cf-3bda51351ed3.JPG)

**Comment by jokva** [comment]
False with capital F. :--)

**Comment by Nagaraju10** [comment]
Many thanks for your quick support. I am still getting the attached error even if I use 'False' attached the error
![error_stict](https://user-images.githubusercontent.com/66116134/83257454-7910e100-a1c5-11ea-8249-b3acab831485.JPG)

**Comment by ErlendHaa** [comment]
The strict option is not a part of the current release (v0.1.16) [1]. It is implemented however [2], and will be part of the _next_ release. 

While waiting for the next release you can build dlisio from source, see [README](https://github.com/equinor/dlisio#build-dlisio)

[1]  https://dlisio.readthedocs.io/en/stable/dlisio.html#dlisio.plumbing.Frame.curves
[2] https://dlisio.readthedocs.io/en/latest/dlisio.html#dlisio.plumbing.Frame.curves

**Comment by Nagaraju10** [comment]
Many thanks for quick response. Can I ask you, When are you releasing version 2? Is there any tentative date ?

**Comment by ErlendHaa** [comment]
There is no set date.  We are waiting for a few final additions before we draft a new release, but I expect that to be in the very near future.

**Comment by ErlendHaa** [comment]
A new release (v0.2.1) is out, which includes the strict option. Closing this issue now, but feel free to re-open if needed

**Comment by Nagaraju10** [comment]
Thank you for  this. I will check  and come back to you.
