### ISSUE TITLE
 Can not read 1 bytes only 0 left

### ISSUE THREAD

**Issue by kumarvvin** [equinor/dlisio#282]
For around 100 dlis files i am getting an error 

  File "C:\ProgramData\Anaconda3\lib\site-packages\dlispy\common.py", line 26, in readBytes
    raise Exception('Can not read {} bytes only {} left'.format(n, len(r)))

Exception: Can not read 1 bytes only 0 left

Similarly : 
Can not read   5456 bytes only 4620 left
Can not read   8184 bytes only 7352 left

**Comment by ErlendHaa** [comment]
Hi

This is dlisio, not dlispy which you are using. You probably meant to post the issue over there: https://github.com/Teradata/dlispy/issues
