### ISSUE TITLE
Fail to interpret SequenceNumber of SU

### ISSUE THREAD

**Issue by kumarvvin** [equinor/dlisio#283]
Some dlis file have this error

  File "C:\ProgramData\Anaconda3\lib\site-packages\dlispy\StorageUnitLabel.py", line 63, in parse
    raise Exception('Fail to interpret SequenceNumber of SU from value [{}]'.format(value))

Exception: Fail to interpret SequenceNumber of SU from value [b'\x00\x00\x00\x00']

**Comment by ErlendHaa** [comment]
Hi

This is dlisio, not dlispy which you are using. You probably meant to post the issue over there: https://github.com/Teradata/dlispy/issues
