### ISSUE TITLE
dlisio docs 

### ISSUE THREAD

**Issue by edirnandi** [equinor/dlisio#284]
Hello there,
First of all thanks for creating this dlisio, first time for me to work through with dlisio and i've just tried to use it, read a couple DLIS files and I can tell you that so far it's working fine. I will try further as I have quite intense experience dealing with DLIS and other digital well log format.

As for the doc,  I read the DLIS format from https://dlisio.readthedocs.io/en/stable/rp66v1.html#id2 , first paragraph about POSC mentioned stands for Petroleum Open Standards Consortium, according to POSC now Energistics, POSC stands for  Petrotechnical Open Software Corporation.   please rectify/update it accordingly.  Thanks again!

**Comment by ErlendHaa** [comment]
Hi!

Great to hear that you find the library useful. The library are still in development and we appreciate any kind of feedback that can help improving it, including feature requests, issues, bug reports. Feel free to post any issues you might have in the issue tracker here on GitHub and we will gladly assist.

It is true that Petroleum Open Standards Consortium was the original name. However they [changed](https://www.energistics.org/about-us/energistics-history/) the meaning of POSC in 2004 to stand for Petrotechnical Open Standards Consortium. Anyway, our docs are still wrong as they say Petroleum not Petrotechnical.

**Comment by edirnandi** [comment]
thanks!
