### ISSUE TITLE
FYI: dliso run from Windows 10 console is fine

### ISSUE THREAD

**Issue by edirnandi** [equinor/dlisio#285]
![dlisio_validate](https://user-images.githubusercontent.com/68481205/87861458-0ca59900-c94f-11ea-9515-1e729dc961a6.JPG)

FYI: dliso run from Windows 10 console is fine

**Comment by ErlendHaa** [comment]
Hi

Thanks for the feedback.

The issue-tracker is mainly intended for reporting issues, bugs or feature-request. We use it to have a transparent conversation about these topics. To keep the list of open issues up to date with the current state of the library, we close any resolved issues. 

As there is no issue here, I will close it. Feel free to use the issue tracker for any of the aforementioned topics :)
