### ISSUE TITLE
Request information about exact variables (Parameters, Curve names/details)

### ISSUE THREAD

**Issue by debasisc-opa** [equinor/dlisio#314]
The following steps work fine to display parameters when I run from Jupyter Notebook -

Step-9 -
`display(desc_table)`

Step-12
`channel_table.sort_values('Name')`

My question -
For both of these, can you please provide equivalent print commands similar to these? Also point me to suitable documentation for this.
```
    print(f'Indexed by       : {frame.index_type}')
    print(f'Interval         : [{frame.index_min}, {frame.index_max}] {index_channel.units}')
```
My goal is to use separate "print" commands to format/present output as per my requirement.
As such, I would prefer to run using IDLE (display(desc_table) in step-9 had to be commented).

Parameter name - Name, Long name, Value
Curve name - Name, Long name. Units

Thank you

**Comment by ErlendHaa** [comment]
Hi,

I assume you are working with [dlisio-notebook](https://github.com/equinor/dlisio-notebooks/blob/master/acoustic.ipynb). I'm not completely sure what you are asking here, but printing is generally out-of-scope of dlisio. In the notebook you can tweak the call to the `summary`-function to add extra fields (e.g. `index_type`) as columns in the DataFrame. After `summary` it's all pandas and I would advice you to check out their documentation for further reading

**Comment by debasisc-opa** [comment]
@ErlendHaa - Thank you. 
Step-9 - For working in IDLE, I could simply use "print" to show the content of dataframe.
`print(desc_table)`

Step-12 - thanks for indicating "pandas" documentation.
After reading relevant documentation, I could achieve my objective by using code such as this.

```
for n in range (0, len(frame.channels)-1):
	print(channel_table['Name'][n])
	print(channel_table['Long name'][n])
	print(channel_table['Units'][n])
	print()


```

**Comment by debasisc-opa** [comment]
Thanks for your help @ErlendHaa
