### ISSUE TITLE
Where to find the multiplier value for channel.units or spacing?

### ISSUE THREAD

**Issue by sgallant-kdm** [equinor/dlisio#365]
Hello, many DLIS have a multiplier value associated to channel.units or what the Schlumberger toolkit "Verification Listing" reports under "Spacing" like f.ex: 60.0 (0.1 in) which equates to a Sample Rate of (6 in).  When I first encountered this, the multiplier of 0.1 can be found directly within the channel.units value like '0.1 in'... no issues.

I've since encountered several DLIS where no multiplier exists within channel.units but the Schlumberger toolkit "Verification Listing" still reports like 60.0 (0.1 in).  dlisio only reports 'in' within channel.units.

Reading through all the dlisio objects, I've not been able to find where this multiplier can be read from... other than channel.units, where else might I find this multiplier value?

Any help locating this would be greatly appreciated!!

**Comment by ErlendHaa** [comment]
Hi

[Frame.spacing](https://dlisio.readthedocs.io/en/stable/dlis/api.html#dlisio.dlis.Frame.spacing) might be a place to look. It refers to the constant spacing of the _index_-channel of the frame. Although not very well documented, all object attributes have their own units. dlisio doesn't have a good interface for reaching them atm, but they are reachable:
```
>>> spacing = frame.attic['SPACING']
>>> spacing.units
'0.1 in'
```

**Comment by sgallant-kdm** [comment]
Thank-you @ErlendHaa !  I can find the missing multiplier here, much appreciated! :)

**Comment by sgallant-kdm** [comment]
Good day @ErlendHaa, if you could help answer one more question please... it appears Schlumberger always reports "Start" & "Stop" from each frame's index channel.curves[0] and channel.curves[-1] (first and last curves) INSTEAD of frame.index_min & frame.index_max.
I can see very often from very many example DLIS that these 2 sets of values are often different but Schlumberger always reports from the channel.curves[].  So I'm not clear, what is the use of frame.index_min & frame.index_max??
I do often notice the (index) channel.curves[] can be the frame.index_min/max * multiplier_value_from_above but this makes no sense to me.
Or often frame.index_min == channel.curves[-1] and frame.index_max == channel.curves[0] but this also makes no sense to me.
Hoping you can enlighten me somewhat??
