### ISSUE TITLE
AttributeError: 'LogicalFile' object has no attribute 'curves'"

### ISSUE THREAD

**Issue by BGogoi2** [equinor/dlisio#387]
I am using the code from the tutorial-
with dlis.load("filename") as files:
	for f in files:
		for frame in f.frames:
			curves = f.curves()

But it is saying "AttributeError: 'LogicalFile' object has no attribute 'curves'"
How to encounter this problem?

**Comment by achaikou** [comment]
Hi!
Notice that [curves](https://dlisio.readthedocs.io/en/latest/dlis/api.html#dlisio.dlis.Frame.curves) is a method on Frame (_frame_), not on LogicalFile (_f_).

Below should work


```
with dlis.load("filename") as files:
    for f in files:
        for frame in f.frames:
            curves = frame.curves()
```

**Comment by BGogoi2** [comment]
Thank you so much! It works. Could you also change the code in the tutorial example so that it becomes helpful for the new users?

**Comment by achaikou** [comment]
Thank you for pointing that out, done!
