### ISSUE TITLE
DLIS WELL Data extraction

### ISSUE THREAD

**Issue by abhishekbyroju** [equinor/dlisio#389]
Can we extract well site data and job data from DLIS file as I dont see any attribute name other than file header, origin, etc?

**Comment by achaikou** [comment]
Hi,

I am not sure what you actually mean by well site data and job data?

If you mean the [curves data](https://dlisio.readthedocs.io/en/latest/dlis/userguide.html#frames-and-channels) aka usually the main content of the file, you need to call `my_frame.curves()` method on every frame in your logical file.

It can also happen that file that you check has no frames, thus no curves data.
You can call [`my_logical_file.describe()`](https://dlisio.readthedocs.io/en/latest/dlis/api.html#dlisio.dlis.LogicalFile.describe) to see what other useful objects apart from FileHeader and Origin exist in your particular file.

If you need full API reference, you can find it [here](https://dlisio.readthedocs.io/en/latest/dlis/api.html).
