### ISSUE TITLE
Not able to extract the producer_name of the logical file from dlisio.

### ISSUE THREAD

**Issue by AchyuthB** [equinor/dlisio#390]
Hi,
I am not able to extract the "producer_name" of the logical file from dlisio.
The document says it belongs to the class _dlisio.dlis.Origin(BasicObject)_ .
If I do `logical_file.types.get('ORIGIN').producer_name`,  I am able to access the property, but not its value.
![image](https://user-images.githubusercontent.com/4114497/128980641-1b033313-396e-4c9f-bdc1-77b5fed3361d.png)

Any help highly appretiated.

Regards
Achyuth

**Comment by achaikou** [comment]
Hi Achyuth!

You issue is that you are using internal attribute [`types`](https://dlisio.readthedocs.io/en/latest/dlis/api.html#dlisio.dlis.LogicalFile.types) which is not intended for getting the data.

Intended ways of accessing objects are described in our [user documentation](https://dlisio.readthedocs.io/en/latest/dlis/userguide.html#accessing-objects), which might be useful for you if you intend to work more with dlisio.

So you can do
```
for origin in logical_file.origins:
    print(origin.producer_name)
```

or, equivalent,

```
for origin in logical_file.find("ORIGIN")
    print(origin.producer_name)
```

**Comment by AchyuthB** [comment]
Hi Alena,

It worked like charm. Thank you so much. :) 
Sorry for the late reply. 

Regards
Achyuth
