### ISSUE TITLE
searched 200 bytes, but could not find visible record envelope pattern [0xFF 0x01]

### ISSUE THREAD

**Issue by soso-maitha** [equinor/dlisio#391]
Hello,

We have been using dlisio library since a year, it works perfectly for 4 vendors (Baker, Schlumberger, Halliburton and Weatherford. However for 5th vendor we are getting the following error in the dlisio.load (dlisio.dlis.load) function. 
We would your support as we need to solve the issue.

Thanks in advance

`---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-272-7c658c876490> in <module>
     19 filePath = path + fileName
     20 print(filePath)
---> 21 f_logical_file, *tail = dlisio.load(filePath)
     22 
~\AppData\Local\Continuum\anaconda3\lib\site-packages\dlisio\load.py in load(path, error_handler)
    106     try:
    107         tapemarks = core.hastapemark(stream)
--> 108         offset = core.findvrl(stream, offset)
    109 
    110         # Layered File Protocol does not currently offer support for re-opening
RuntimeError: searched 200 bytes, but could not find visible record envelope pattern [0xFF 0x01]
`

**Comment by soso-maitha** [comment]
hello,

Thanks for your response. is there any function in dlisio library that extracts the first ~500 bytes using dlisio ? if i can get the piece of code that does that would be great. or i should i write it from scratch independently from dlisio library  ?

**Comment by ErlendHaa** [comment]
Hi,

You'll have to do that without dlisio. If you are on linux or max you can run: `hexdump -Cv -n 500 your_file.dlis` in the terminal. On windows, I think you could get some third-party library, e.g. https://pypi.org/project/hexdump/ to do the job

**Comment by soso-maitha** [comment]
noted. thanks i will try

**Comment by soso-maitha** [comment]
hi,
we tried with latest dlisio version dlisio.lis.load, we found that these files are LIS files not DLIS. Thank you so much!

regards,

**Comment by ErlendHaa** [comment]
Right, another case of file extensions that lie  ¯\_(ツ)_/¯
