### ISSUE TITLE
Duplicated Mnemonics on LIS files.

### ISSUE THREAD

**Issue by rodiegeology** [equinor/dlisio#392]
Tha same issue presented here https://github.com/equinor/dlisio/issues/95 for DLIS files is occuring with me when reading LIS files, is there any workaround this issue like changing the mnemonic name or something like it? I just want to retrieve the mnemonics, not the curves. 

"ValueError: field 'CALI' occurs more than once"

**Comment by ErlendHaa** [comment]
Mnemonics are just metadata, so you can grab them without out going through `.curves(f, dfsr)` or `.curves_metadata(f, dfsr)`. E.g. `mnems = [x.mnemonic for x in dfsr.specs]`. 

Alternatively, check out the [strict option](https://dlisio.readthedocs.io/en/latest/lis/api.html#lis-curves) in `.curves()` and `.curves_metadata()`
