### ISSUE TITLE
Parameter value is decoded strangely

### ISSUE THREAD

**Issue by ejschoen** [equinor/dlisio#397]
Using either dlisio 0.3.1 or 0.3.5, I was doing some random quality control on files we use for testing from the Equinor Volve dataset, and stumbled across a strangely decoded parameter.

The file from Volve is Well_logs/02.LWD_EWL/15_9-F-11 T2/WL_RAW_AAC_MWD_2.DLIS.  

In the first logical file, or at least the one with ID BAKERH_00001, there's a parameter with name "FL", long name: Field Location, whose value decodes as an ndarray of type string, but whose contents render as:

['\ue64d獲\u206b湉灳物牥']

Attached below is a screen shot out of Pycharm of the parameter object.  Any thoughts as to how to properly decode that value?  I'm curious as to whether there is a well location relative to a geodetic coordinate system such as WGS-84 hiding there, or if it's just uninitialized random noise in the file.

![Screen Shot 2021-11-08 at 11 41 14 AM](https://user-images.githubusercontent.com/10605666/140791414-7f1facf5-74be-4280-be71-fc949fe7f24b.png)

**Comment by achaikou** [comment]
Hi!

I believe you [set the encoding](https://dlisio.readthedocs.io/en/stable/common-api.html#strings-and-encodings) to UTF-16, which appears not to be good for this particular string.

Many files do not adhere to specification and use characters past the ASCII range. So it's never clear which exact encoding one needs to apply in such cases to restore information as it was intended, but country of origin might somewhat help with guessing.

I believe in your case setting latin1 encoding should work. 
`dlisio.common.set_encodings(['latin1'])`

**Comment by ejschoen** [comment]
Thanks!  That was it.  We had this in our initialization code:
     dlisio.common.set_encodings(['utf-8','utf-16','latin1'])
If I put latin1 before utf-16, the result makes much sense:
    Mærsk Inspirer
