### ISSUE TITLE
How to extract 'Sequence' and 'Producer code' details from an LIS file?

### ISSUE THREAD

**Issue by AchyuthB** [equinor/dlisio#398]
Hi,

Using dlisio.dlis module, from a DLIS file, I am able to extract sequence information as 
`logical_file.fileheader.sequencenr`

The Origin details I was able to extract using 
`logical_file.origins[0]`

But for LIS files (using dlisio.lis), I don't see any details regarding extracting those in their [API documentation](https://dlisio.readthedocs.io/en/latest/lis/api.html).

Any help regarding this is highly appreciated. 

Regards
Achyuth

**Comment by ErlendHaa** [comment]
There is not a 1-to-1 mapping between metadata in LIS and DLIS, but this type of information is typically found the [File Header](https://dlisio.readthedocs.io/en/latest/lis/api.html#file-header-fhlr), [Tape Header](https://dlisio.readthedocs.io/en/latest/lis/api.html#tape-header-thlr) and [Reel Header](https://dlisio.readthedocs.io/en/latest/lis/api.html#reel-header-rhlr). Sequencenr doesn't really make sense, as the concept Storage Set doesn't exist in LIS. There is also a lot of metadata in the Job Identification-, Tool String Info- and Wellsite Data-records, but these are far less structured and what vendors put there varies
