### ISSUE TITLE
Missing "index_mnem" in the Data Format Specification Record (DFSR)

### ISSUE THREAD

**Issue by AchyuthB** [equinor/dlisio#400]
Hi,

The [LIS API Reference](https://dlisio.readthedocs.io/en/latest/lis/api.html#dlisio.lis.DataFormatSpec.specs) mentions about the property "index_mnem" and "index_units", both of which are missing in my DataFormatSpec class property. Other properties mentioned in the reference docuement are available.

![image](https://user-images.githubusercontent.com/4114497/143023760-ee80c0ef-b222-40ef-a604-21c7fbbd4570.png)

Is there any other way to get the DataFormatSpec name from an LIS file.

Thanks
Achyuth

**Comment by ErlendHaa** [comment]
Hi,

Which dlisio version are you using?

**Comment by AchyuthB** [comment]
dlisio==0.3.4

**Comment by AchyuthB** [comment]
Hi @ErlendHaa,

I just checked the [changelog](https://dlisio.readthedocs.io/en/latest/changelog.html?highlight=0.3.5#id1). These properties are added in the version 0.3.5. I have 0.3.4. 
Will update to the latest version of dlisio. 

Thank you so much for pointing this out.

Regards
Achyuth

**Comment by AchyuthB** [comment]
Hi,

I upgraded the dlisio to version to 0.3.5. Now I get error while calling "_logical_file.data_format_specs():_"
It says
`AttributeError("'dlisio.core.lis_stream' object has no attribute 'read_records'")`

Any help is highly appretiated.

Thanks
Achyuth

**Comment by ErlendHaa** [comment]
#401
