### ISSUE TITLE
How to access header information in unstructured LIS files?

### ISSUE THREAD

**Issue by lucasaguiar26** [equinor/dlisio#409]
I would like to access header information from LIS files, as API/APIN number. I can do this in structured LIS files as I can read this information as a table, although I can't do that in unstructured files.

The documentation indicates that this unstructured files can be read "as a list of single parameter values", but I still can't pick the information I want inside of this list.

Does anyone know how can I manipulate this list or could I convert this information to a table as structured LIS files?

**Comment by ErlendHaa** [comment]
Hi!

I assume you are talking about the [Information Records](https://dlisio.readthedocs.io/en/latest/lis/userguide.html#tables-in-information-records). In that case, maybe https://github.com/equinor/dlisio/issues/404 can shed some light on the matter?

**Comment by lucasaguiar26** [comment]
You are right. #404 really helped me to understand better these file structures. Thank you very much!

LIS files can be tricky to work with
