### ISSUE TITLE
Is there a way to write?

### ISSUE THREAD

**Issue by weipeng404** [equinor/dlisio#417]
Hello, thanks for creating the library and I've been using it to read DLIS files. I'm wondering if there's a way to write new frames and channels back to a DLIS file?

**Comment by ErlendHaa** [comment]
Hi! Unfortually, no. dlisio does not support writing at the moment. There are currently no plans to implement writing support I'm afraid.

**Comment by weipeng404** [comment]
Okay, thanks for the reply anyway.
