### ISSUE TITLE
Installation on Alpine linux 

### ISSUE THREAD

**Issue by rkhabbaz** [equinor/dlisio#426]
Hi, 
I appreciate any help to install dlisio on Alpine linux. I am getting error below.
<img width="825" alt="Screenshot 2023-08-21 at 12 32 33" src="https://github.com/equinor/dlisio/assets/39388027/52a5fd3a-0f15-4eaf-a78f-77bb0bbd0e78">

I am using Alpine as a base image for a containerised app which depends on dlisio. Here is a simplified version of the Dockerfile:
 
<img width="881" alt="Screenshot 2023-08-21 at 12 32 21" src="https://github.com/equinor/dlisio/assets/39388027/e40b1f7b-a69c-441e-a008-9f215519dea8">

**Comment by rkhabbaz** [comment]
Hi Alena,

Thank you so much. indeed it works like a charm. 
I changed it a bit to clean up after the installation. I share it here in case someone is interested.

# Base image 
FROM python:3.10-alpine

RUN apk -U upgrade --no-cache \
    && apk add --no-cache git make cmake g++ \
    && pip install --upgrade pip


# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1


#mpark variant
WORKDIR /tmp
RUN git clone https://github.com/mpark/variant.git
WORKDIR /tmp/variant/build
RUN cmake -DCMAKE_BUILD_TYPE=Release .. \
    && make -j4 \
    && make install 

#fmt
WORKDIR /tmp
RUN git clone https://github.com/fmtlib/fmt.git
WORKDIR /tmp/fmt/build
RUN git checkout 7.1.3 \
    && cmake -DFMT_TEST=OFF -DFMT_DOC=OFF .. \
    && make -j4 \
    && make install 

#lfp
WORKDIR /tmp
RUN git clone https://github.com/equinor/layered-file-protocols.git
WORKDIR /tmp/layered-file-protocols/build
RUN cmake -DBUILD_SHARED_LIBS=ON -DLFP_FMT_HEADER_ONLY=ON -DCMAKE_INSTALL_NAME_DIR=/usr/local/lib -DBUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=Release .. \
    && make -j4 \
    && make install 

#dlisio
WORKDIR /tmp
RUN git clone https://github.com/equinor/dlisio.git
WORKDIR /tmp/dlisio
RUN git checkout v1.0.0 \
    && pip install -r python/requirements-dev.txt
WORKDIR /tmp/dlisio/build
RUN cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_NAME_DIR=/usr/local/lib .. \
    && make -j4 \
    && make install

# Remove unwanted files and folders created during the last 4 layers in /tmp
WORKDIR /tmp
RUN rm -rf *

# Remove unwanted packages after building dlisio from source
RUN apk del git make cmake

**Comment by achaikou** [comment]
FYI: for version 1.0.1 musllinux x86_64 wheels are supplied through pip, so there should be no need anymore to build from source for docker on standard architecture.
