### ISSUE TITLE
Measure trade-off for findoffsets

### ISSUE THREAD

**Issue by achaikou** [equinor/dlisio#74]
Suggestion is to write some kind of tests to measure trade-off for used memory and time (number of reallocations) for findoffsets feature. 
Suggested parameters:
- Initial logical record size guess (currently 4K)
- Growth factor (currently 1.5)

Measure:
- time of indexing
- how much memory we take during indexing.

Note:
Acceptable memory size during indexing of 3.5GB file is couple of 10MB. 100MB is too much.

**Comment by ErlendHaa** [comment]
NA
