### ISSUE TITLE
Consistent model for missing or absent attributes

### ISSUE THREAD

**Issue by achaikou** [equinor/dlisio#89]
Current situation:

1. 
count = 0, value bit not set
f.objects[key].attic["MY_ATTRIBUTE"] == []

2.
count = 0, value bit set (no value provided, obviously)
f.objects[key].attic["MY_ATTRIBUTE"] == None

3.
if MY_ATTRIBUTE is marked as absent in object,
f.objects[key].attic["MY_ATTRIBUTE"] will throw KeyError

Plan is to make cases 1 & 2 both return None, but behaviour should be revisited as we need a consistent model for missing or absent attributes.

**Comment by ErlendHaa** [comment]
This is a minor detail that is unlikely to affect anybody
