### ISSUE TITLE
Better dealing with duplicated mnemonics when retrieving log values

### ISSUE THREAD

**Issue by rmorel** [equinor/dlisio#95]
When I try to load the curve values from a frame with repeated mnemonics, something like:

> `fingerprint = fr.fingerprint # A frame fingerprint`
> `curves = f.curves(fingerprint) # Load all curves`

I get the following error: `ValueError: field 'SPT4' occurs more than once`. SPT4 may be any duplicated mnemonic.

This kind of issue is really common with DLIS files. I suggest using the [same approach from lasio](https://lasio.readthedocs.io/en/latest/_modules/lasio/las_items.html),  any duplicates will have ':1', ':2', ':3', etc., appended to them. 

That way the API user can inspect the data and decide what which logs he really wants to work with.

I'm using DLISIO version 0.1.4, installed directly using pip.

**Comment by jokva** [comment]
Hi,

We're checking if the mnemonics are duplicated _and identical_. If they are, we simply ignore the consecutive copies, and I honestly can't see why they'd be interesting at that point.

When mnemonics are duplicated _but not equal_ we currently warn and pick the last one. Adding a suffix, or maybe putting them in a special member, would be a decent solution I guess. We never throw away the source, though, it's intended to be available, if a bit cumbersome.

**Comment by jokva** [comment]
Oh right, this is probably from numpy, with duplicated column labels on frames. Yes, we could maybe do something like that for the numpy labels - or, we can use the origin and copynumber instead of :1, :2, [...] as DLIS already has this disambiguation mechanism built in.

**Comment by rmorel** [comment]
@jokva thanks for the reply. Indeed I was referring to the numpy labels.

I recommend care when using the copynumber directly, since you may create odd scenarios with TDEP and TIME mnemonics.

Here is an example of a frame structure from a DLIS I'm working with:

```
Frame:  dlisio.core.obname(id='B414452', origin=0, copynum=0)
	Channel: dlisio.core.obname(id='TDEP', origin=0, copynum=1)
	Channel: dlisio.core.obname(id='DTCO', origin=0, copynum=0)
	Channel: dlisio.core.obname(id='SPT4', origin=1, copynum=0)
	Channel: dlisio.core.obname(id='SPR4', origin=1, copynum=0)
	Channel: dlisio.core.obname(id='SPT4', origin=1, copynum=1)
	Channel: dlisio.core.obname(id='SPR4', origin=1, copynum=1)
```

In this case, using copynumber will make the numpy labels as follows ```['TDEP:1', 'DTCO', 'SPT4', 'SPR4', 'SPT4:1', 'SPT4:1']``` which may be counter intuitive for the TDEP mnemonic.

Maybe we can use the copy number except for the TDEP and TIME mnemonics? I can't say for sure, but I think that you may drop duplicated versions from these two mnemonics from the numpy array without further problems (data losses, etc).

**Comment by rmorel** [comment]
On second thought, I think that your suggestion may be a better approach, since it (as you said) keeps in line with DLIS disambiguation mechanisms and having a available mnemonics list from a frame is as simple as:
```
for fr in f.frames:
    channels = ['{}:{}'.format(ch.name.id, ch.name.copynumber) for ch in fr.channels]
```

**Comment by jokva** [comment]
Yes, that's one pretty obvious way of doing it. The only issue with a label:origin:copy format is that it's pretty ugly to work with, if maybe more predictable. My hunch is that it's a lot prettier to just introduce the origin and copynumber (but at that point both) only when we have duplicate labels.

It should be simple to implement, I'll probably get it done tomorrow.

**Comment by jokva** [comment]
For what it's worth, you can work around the issue by manually updating the column names in the `frame.dtype` variable. If you do that, you should be able to read the curves.

**Comment by rmorel** [comment]
I also think that is a good idea.

I'm following the repository updates and using DLISIO to read a lot of DLIS files, so once you implement the changes I can test it and give you some feedback.

> Yes, that's one pretty obvious way of doing it. The only issue with a label:origin:copy format is that it's pretty ugly to work with, if maybe more predictable. My hunch is that it's a lot prettier to just introduce the origin and copynumber (but at that point both) only when we have duplicate labels.
> 
> It should be simple to implement, I'll probably get it done tomorrow.

**Comment by jokva** [comment]
@rmorel I've uploaded 0.1.5 which, amongst other things, includes a fix for duplicated mnemonics. Mind trying it out?

**Comment by rmorel** [comment]
@jokva unfortunately I'm out of the office at the moment due to a sick leave, but early next week I'll be able to test the changes without further delay.

Anyway, thanks for implementing things so quickly =)
